name: aipl-testing
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  run-tests:

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip3 install .
        pip3 install pytest

    - name: Ensure it exe starts up
      run: aipl -h

    - name: Run pytests
      run: pytest tests/ aipl/ aipl/ops/*.py
